---
# Source: cubesandbox/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cubesandbox-secret
  namespace: cube-system
  labels:
    helm.sh/chart: cubesandbox-1.0.0
    app.kubernetes.io/name: cubesandbox
    app.kubernetes.io/instance: cubesandbox
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  mysql-root-password: "root_pass"
  mysql-password: "cube_pass"
  redis-password: "ceuhvu123"